// <auto-generated />
using System;
using LeBot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeBot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LeBotDbContext))]
    [Migration("20260628063321_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("LeBot.Application.Telemetry.RepostEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BotVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ElapsedMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorVariant")
                        .HasColumnType("TEXT");

                    b.Property<string>("Extractor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("MediaBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Host");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("Outcome");

                    b.ToTable("RepostEvents", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
